# Generated by Django 5.0.4 on 2024-05-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingpsico', '0003_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
